/**
 * lib/export/bracket-pdf.ts
 * Printable playoff-bracket sheet — jsPDF, lazy-loaded client-side.
 *
 * Unlike the tabular reports in pdf.ts, a bracket is drawn as round columns of
 * matchup boxes (via the shared bracketRoundInfo grouping). Played games show
 * scores with the winner bolded; un-played games show a blank fill-in line, so
 * the same export works as a draw-day sheet or a live bracket.
 *
 * Double elimination draws as a FORK (seed round → winners on top / losers on
 * the bottom → grand final on the right), matching the on-screen bracket. When
 * the fork can't hold a legible column width on one landscape page, it splits
 * across two pages (Winners, then Losers); over-wide flat brackets paginate by
 * round. Connectors follow the Winner/Loser references and are coloured by path.
 */

import { DEFAULT_PDF_SETTINGS, type OrgPdfSettings } from './pdf';
import { bracketRoundInfo, computeBracketColumns, displayBracketRefs, displayRoundTitle, groupGamesByBracketId } from '@/lib/playoff-bracket';
import type { Game, Team } from '@/lib/types';

const NIL_UUID = '00000000-0000-0000-0000-000000000000';
const BRANDING_TEXT = 'Generated by FieldLogicHQ';

function hexToRgb(hex: string): { r: number; g: number; b: number } {
  const clean = (hex || '').replace('#', '');
  const full = clean.length === 3 ? clean.split('').map(c => c + c).join('') : clean;
  return {
    r: parseInt(full.slice(0, 2), 16) || 0,
    g: parseInt(full.slice(2, 4), 16) || 0,
    b: parseInt(full.slice(4, 6), 16) || 0,
  };
}

function sideName(teamId: string | null | undefined, placeholder: string | undefined, teams: Team[]): string {
  if (teamId && teamId !== NIL_UUID) {
    const t = teams.find(tm => tm.id === teamId);
    if (t) return t.name;
  }
  return placeholder || 'TBD';
}

interface BracketColumn { title: string; games: Game[]; }

function buildColumns(games: Game[]): BracketColumn[] {
  const colMap = computeBracketColumns(games);
  const groups = new Map<string, { title: string; rank: number; games: Game[] }>();
  for (const g of games) {
    const info = colMap.get(g.id) || bracketRoundInfo(g.bracketCode || '');
    let grp = groups.get(info.key);
    if (!grp) { grp = { title: info.title, rank: info.rank, games: [] }; groups.set(info.key, grp); }
    grp.games.push(g);
  }
  return [...groups.values()]
    .sort((a, b) => a.rank - b.rank)
    .map(grp => ({ title: grp.title, games: grp.games.sort((a, b) => (a.bracketCode || '').localeCompare(b.bracketCode || '')) }));
}

function isDecided(g?: Game): boolean {
  return !!g && (g.status === 'completed' || g.status === 'submitted')
    && g.homeScore != null && g.awayScore != null && g.homeScore !== g.awayScore;
}

function sectionOfColumn(col: BracketColumn): 'W' | 'L' | 'GF' {
  const code = (col.games[0]?.bracketCode || '').toUpperCase();
  if (code.startsWith('LB')) return 'L';
  if (code.startsWith('GF')) return 'GF';
  return 'W';
}

function wbRoundOfColumn(col: BracketColumn): number {
  const m = (col.games[0]?.bracketCode || '').toUpperCase().match(/^WB(\d+)/);
  return m ? parseInt(m[1], 10) : 0;
}

/**
 * Build + download a printable bracket PDF for a division's playoff games.
 */
export async function downloadBracketPDF(
  filename: string,
  title: string,
  subtitle: string | undefined,
  games: Game[],
  teams: Team[],
  settings: OrgPdfSettings = DEFAULT_PDF_SETTINGS,
  /** Blank fill-in bracket: empty name + score lines on every slot (print & fill
   *  in by hand). Structure still reads from round titles, codes, and connectors. */
  blank: boolean = false,
): Promise<void> {
  const { default: jsPDF } = await import('jspdf');

  const playoffGames = games.filter(g => g.isPlayoff);
  // Split into independent brackets (tiers / per-pool): each bracket_id renders as
  // its own section so tiers print as separate, titled brackets instead of merging
  // into one cross-wired tree. A single bracket → one group (unchanged output).
  const groups = groupGamesByBracketId(playoffGames);

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const doc: any = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'letter' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 12;
  const accent = hexToRgb(settings.accentColor || '#1e293b');

  // The current section's champion (recomputed per bracket group) + its tier label,
  // both read by drawPageHeader's closure.
  let championName: string | null = null;
  let groupLabel: string | undefined;

  // ── Header (drawn per page) ───────────────────────────────────────────────
  const drawPageHeader = (suffix?: string): number => {
    doc.setFillColor(accent.r, accent.g, accent.b);
    doc.rect(0, 0, pageW, 7, 'F');

    let textX = margin;
    if (settings.logoDataUrl) {
      try {
        const fmt = settings.logoDataUrl.startsWith('data:image/png') ? 'PNG' : 'JPEG';
        doc.addImage(settings.logoDataUrl, fmt, margin, margin, 20, 10);
        textX = margin + 24;
      } catch { /* skip logo on failure */ }
    }
    doc.setFont('helvetica', 'bold'); doc.setFontSize(14); doc.setTextColor(20, 20, 35);
    doc.text(settings.headerLine1 || title, textX, margin + 5);
    doc.setFont('helvetica', 'normal'); doc.setFontSize(9); doc.setTextColor(90, 90, 110);
    doc.text([title, subtitle, groupLabel, suffix].filter(Boolean).join('  ·  '), textX, margin + 11);

    if (championName) {
      doc.setFont('helvetica', 'bold'); doc.setFontSize(11); doc.setTextColor(accent.r, accent.g, accent.b);
      doc.text(`Champion: ${championName}`, pageW - margin, margin + 6, { align: 'right' });
    }

    const hb = margin + 15;
    doc.setDrawColor(210, 210, 220); doc.setLineWidth(0.3);
    doc.line(margin, hb, pageW - margin, hb);
    return hb;
  };

  // ── Footer (drawn per page) ───────────────────────────────────────────────
  const drawFooter = () => {
    const footerY = pageH - 6;
    doc.setFont('helvetica', 'normal'); doc.setFontSize(7); doc.setTextColor(140, 140, 155);
    const parts: string[] = [];
    if (settings.footerText) parts.push(settings.footerText);
    if (settings.showDateStamp) parts.push(`Exported: ${new Date().toISOString().split('T')[0]}`);
    if (settings.showBranding) parts.push(BRANDING_TEXT);
    if (parts.length) doc.text(parts.join('  ·  '), margin, footerY);
  };

  if (playoffGames.length === 0) {
    const hb = drawPageHeader();
    doc.setFont('helvetica', 'normal'); doc.setFontSize(11); doc.setTextColor(120, 120, 135);
    doc.text('No playoff bracket games to display.', margin, hb + 12);
    drawFooter();
    doc.save(filename);
    return;
  }

  // ── Shared geometry ───────────────────────────────────────────────────────
  const colGap = 6;
  const boxH = 13;
  const rowH = boxH / 2;
  // Below this column width names truncate badly → split across pages instead.
  const MIN_COL_W = 33;

  const truncate = (text: string, maxW: number) => {
    if (doc.getTextWidth(text) <= maxW) return text;
    let t = text;
    while (t.length > 1 && doc.getTextWidth(t + '…') > maxW) t = t.slice(0, -1);
    return t + '…';
  };

  type Placement = { game: Game; x: number; y: number };
  type ConnectorMode = 'data' | 'none';

  // Lay out + draw one set of columns within the current page's body.
  //   • 'fork' → seed (left) → winners (top) / losers (bottom) → grand final (right)
  //   • 'flat' → one row of round columns
  // Connectors:
  //   • 'data' → follow Winner/Loser refs (format-agnostic; single + double elim),
  //              coloured by path, only when both endpoints are on this page.
  //   • 'none' → no lines (consolation / placement cross-links would be noise).
  const drawSection = (cols: BracketColumn[], mode: 'fork' | 'flat', headerBottom: number, connectors: ConnectorMode) => {
    const bodyTop = headerBottom + 9;
    const bodyH = (pageH - 11) - bodyTop;
    const placements: Placement[] = [];
    const headers: { title: string; cx: number; y: number }[] = [];
    let colW = 0;

    if (mode === 'fork') {
      const wbAll = cols.filter(c => sectionOfColumn(c) === 'W');
      const lbCols = cols.filter(c => sectionOfColumn(c) === 'L');
      const gfCols = cols.filter(c => sectionOfColumn(c) === 'GF');
      const seedCols = wbAll.filter(c => wbRoundOfColumn(c) === 1);
      const wbCols = wbAll.filter(c => wbRoundOfColumn(c) !== 1);

      const offset = seedCols.length;                       // seed occupies horizontal column 0
      const mainSpan = Math.max(wbCols.length, lbCols.length);
      const numH = offset + mainSpan + gfCols.length;
      colW = (pageW - margin * 2 - colGap * (numH - 1)) / numH;
      const hX = (h: number) => margin + h * (colW + colGap);

      const bandGap = Math.min(16, bodyH * 0.08);
      const bandH = (bodyH - bandGap) / 2;
      const wbTop = bodyTop;
      const lbTop = bodyTop + bandH + bandGap;
      const forkMid = bodyTop + bodyH / 2;

      const placeBand = (bandCols: BracketColumn[], top: number, h: number, hStart: number) =>
        bandCols.forEach((col, i) => {
          const x = hX(hStart + i);
          headers.push({ title: displayRoundTitle(col.title), cx: x + colW / 2, y: top - 1 });
          const k = col.games.length;
          col.games.forEach((g, gi) => placements.push({ game: g, x, y: top + (h / k) * gi + (h / k) / 2 - boxH / 2 }));
        });

      // Seed round — spread across the full fork height (fills the empty space).
      seedCols.forEach(col => {
        const x = hX(0);
        headers.push({ title: 'Seed Round', cx: x + colW / 2, y: bodyTop - 1 });
        const k = col.games.length;
        col.games.forEach((g, gi) => placements.push({ game: g, x, y: bodyTop + (bodyH / k) * gi + (bodyH / k) / 2 - boxH / 2 }));
      });
      placeBand(wbCols, wbTop, bandH, offset);
      placeBand(lbCols, lbTop, bandH, offset);

      // Grand final (+ "if necessary" reset) — centred on the right, boxes stacked.
      gfCols.forEach((col, gci) => {
        const x = hX(offset + mainSpan + gci);
        const k = col.games.length;
        const stackH = k * boxH + (k - 1) * 5;
        const startY = forkMid - stackH / 2;
        headers.push({ title: displayRoundTitle(col.title), cx: x + colW / 2, y: startY - 4 });
        col.games.forEach((g, gi) => placements.push({ game: g, x, y: startY + gi * (boxH + 5) }));
      });
    } else {
      const numH = Math.max(cols.length, 1);
      colW = (pageW - margin * 2 - colGap * (numH - 1)) / numH;
      const hX = (h: number) => margin + h * (colW + colGap);
      const maxBoxes = Math.max(...cols.map(c => c.games.length), 1);
      const totalH = Math.min(bodyH, (boxH + 14) * maxBoxes);
      const topPad = bodyTop + Math.max(0, (bodyH - totalH) / 2);
      cols.forEach((col, ci) => {
        const x = hX(ci);
        headers.push({ title: displayRoundTitle(col.title), cx: x + colW / 2, y: bodyTop - 1 });
        const k = col.games.length;
        col.games.forEach((g, gi) => placements.push({ game: g, x, y: topPad + (totalH / k) * gi + (totalH / k) / 2 - boxH / 2 }));
      });
    }

    // ── Connectors ──
    if (connectors === 'data') {
      const byCodePos = new Map(placements.map(p => [(p.game.bracketCode || '').toUpperCase(), p]));
      placements.forEach(({ game: g, x, y }) => {
        [g.homePlaceholder, g.awayPlaceholder].forEach(ph => {
          const m = (ph || '').match(/^(Winner|Loser)\s+(.+)$/i);
          if (!m) return;
          const src = byCodePos.get(m[2].toUpperCase());
          if (!src) return;                       // source not on this page → label only
          const loser = m[1].toLowerCase() === 'loser';
          const fromX = src.x + colW, fromY = src.y + boxH / 2;
          const toY = y + boxH / 2;
          const midX = (fromX + x) / 2;
          if (loser) { doc.setDrawColor(217, 142, 10); doc.setLineDashPattern([0.8, 0.8], 0); }
          else { doc.setDrawColor(34, 160, 80); doc.setLineDashPattern([], 0); }
          doc.setLineWidth(0.3);
          doc.line(fromX, fromY, midX, fromY);
          doc.line(midX, fromY, midX, toY);
          doc.line(midX, toY, x, toY);
        });
      });
      doc.setLineDashPattern([], 0);
    }

    // ── Boxes ──
    const drawBox = (g: Game, x: number, y: number) => {
      const played = !blank && (g.status === 'completed' || g.status === 'submitted') && g.homeScore != null && g.awayScore != null;
      const homeWin = played && (g.homeScore ?? 0) > (g.awayScore ?? 0);
      const awayWin = played && (g.awayScore ?? 0) > (g.homeScore ?? 0);

      // Round/code label above the box — makes "Winner SR-1" references findable.
      const codeLabel = displayBracketRefs((g.bracketCode || '').toUpperCase());
      if (codeLabel) {
        doc.setFont('helvetica', 'bold'); doc.setFontSize(5.5); doc.setTextColor(150, 150, 165);
        doc.text(codeLabel, x + 1, y - 1.2);
      }

      // Fill white so connectors that pass nearby never bleed through the card.
      doc.setDrawColor(200, 200, 212); doc.setLineWidth(0.3); doc.setFillColor(255, 255, 255);
      doc.roundedRect(x, y, colW, boxH, 1, 1, 'FD');
      doc.setDrawColor(228, 228, 238);
      doc.line(x, y + rowH, x + colW, y + rowH);

      const scoreW = 7;
      const nameMaxW = colW - 4 - scoreW;
      const drawSide = (name: string, win: boolean, rowTop: number, score: number | null | undefined) => {
        if (blank) {
          // Empty fill-in lines for the team name and the score.
          doc.setDrawColor(205, 205, 216); doc.setLineWidth(0.3);
          doc.line(x + 2, rowTop + rowH / 2 + 1.4, x + colW - scoreW - 2, rowTop + rowH / 2 + 1.4);
          doc.line(x + colW - scoreW, rowTop + rowH / 2 + 1.4, x + colW - 2, rowTop + rowH / 2 + 1.4);
          return;
        }
        doc.setFont('helvetica', win ? 'bold' : 'normal');
        doc.setFontSize(7.5);
        doc.setTextColor(win ? 20 : 64, win ? 20 : 64, win ? 35 : 78);
        doc.text(truncate(name, nameMaxW), x + 2, rowTop + rowH / 2 + 1.1);
        if (played) {
          doc.setFont('helvetica', 'bold'); doc.setFontSize(8.5);
          doc.text(String(score ?? ''), x + colW - 2, rowTop + rowH / 2 + 1.2, { align: 'right' });
        } else {
          doc.setDrawColor(205, 205, 216);
          doc.line(x + colW - scoreW, rowTop + rowH / 2 + 1.4, x + colW - 2, rowTop + rowH / 2 + 1.4);
        }
      };
      drawSide(displayBracketRefs(sideName(g.homeTeamId, g.homePlaceholder, teams)), homeWin, y, g.homeScore);
      drawSide(displayBracketRefs(sideName(g.awayTeamId, g.awayPlaceholder, teams)), awayWin, y + rowH, g.awayScore);
    };

    headers.forEach(h => {
      doc.setFont('helvetica', 'bold'); doc.setFontSize(7.5); doc.setTextColor(accent.r, accent.g, accent.b);
      doc.text(h.title.toUpperCase(), h.cx, h.y, { align: 'center', maxWidth: colW + colGap });
    });
    placements.forEach(p => drawBox(p.game, p.x, p.y));
  };

  // ── Render one bracket group (a tier / pool, or the whole single bracket) ────
  const fitColW = (n: number) => (pageW - margin * 2 - colGap * (n - 1)) / n;
  const renderGroup = (groupGames: Game[]) => {
    const columns = buildColumns(groupGames);
    if (columns.length === 0) return;

    // Champion for THIS group (decisive grand-final reset, grand final, or final).
    const byCode = (c: string) => groupGames.find(g => (g.bracketCode || '').toUpperCase() === c);
    const finalG = [byCode('GF2'), byCode('GF'), byCode('FIN')].find(isDecided);
    championName = !blank && finalG
      ? sideName(
          (finalG.homeScore ?? 0) > (finalG.awayScore ?? 0) ? finalG.homeTeamId : finalG.awayTeamId,
          (finalG.homeScore ?? 0) > (finalG.awayScore ?? 0) ? finalG.homePlaceholder : finalG.awayPlaceholder,
          teams,
        )
      : null;

    const isDoubleElim = groupGames.some(g => /^LB/i.test(g.bracketCode || ''));
    const isMultiSection = groupGames.some(g => /^(WB|LB|GF|CON|PL)/i.test(g.bracketCode || ''));

    if (isDoubleElim) {
      const wbAll = columns.filter(c => sectionOfColumn(c) === 'W');
      const lbCols = columns.filter(c => sectionOfColumn(c) === 'L');
      const gfCols = columns.filter(c => sectionOfColumn(c) === 'GF');
      const seedCols = wbAll.filter(c => wbRoundOfColumn(c) === 1);
      const wbCols = wbAll.filter(c => wbRoundOfColumn(c) !== 1);
      const forkNumH = seedCols.length + Math.max(wbCols.length, lbCols.length) + gfCols.length;

      if (fitColW(forkNumH) >= MIN_COL_W) {
        // Fits legibly → the whole fork on one page.
        drawSection(columns, 'fork', drawPageHeader(), 'data');
        drawFooter();
      } else {
        // Too dense → Winners (seed + winners + grand final) on page 1, Losers on
        // page 2. Each gets full page width, so names stay readable.
        drawSection([...seedCols, ...wbCols, ...gfCols], 'flat', drawPageHeader('Winners Bracket'), 'data');
        drawFooter();
        doc.addPage();
        drawSection(lbCols, 'flat', drawPageHeader('Losers Bracket'), 'data');
        drawFooter();
      }
    } else {
      // Single-elim follows the real Winner/Loser wiring ('data'), same as the
      // double-elim fork — so renamed/legacy/irregular brackets trace correctly
      // instead of assuming round-to-round halving.
      const flatConnectors: ConnectorMode = isMultiSection ? 'none' : 'data';
      if (fitColW(columns.length) >= MIN_COL_W || columns.length <= 1) {
        drawSection(columns, 'flat', drawPageHeader(), flatConnectors);
        drawFooter();
      } else {
        // Too many rounds for one page → paginate by round.
        const perPage = Math.max(2, Math.floor((pageW - margin * 2 + colGap) / (MIN_COL_W + colGap)));
        for (let i = 0; i < columns.length; i += perPage) {
          if (i > 0) doc.addPage();
          const last = Math.min(i + perPage, columns.length);
          const suffix = columns.length > perPage ? `Rounds ${i + 1}–${last}` : undefined;
          drawSection(columns.slice(i, last), 'flat', drawPageHeader(suffix), flatConnectors);
          drawFooter();
        }
      }
    }
  };

  // Each bracket group prints on its own page(s); the tier name shows in the header.
  let rendered = false;
  groups.forEach((grp, gi) => {
    if (grp.games.length === 0) return;
    if (rendered) doc.addPage();
    groupLabel = groups.length > 1 ? (grp.label || `Bracket ${gi + 1}`) : undefined;
    renderGroup(grp.games);
    rendered = true;
  });
  // No group produced any columns (e.g. games without resolvable structure) → blank sheet.
  if (!rendered) {
    const hb = drawPageHeader();
    doc.setFont('helvetica', 'normal'); doc.setFontSize(11); doc.setTextColor(120, 120, 135);
    doc.text('No playoff bracket games to display.', margin, hb + 12);
    drawFooter();
  }

  doc.save(filename);
}
