/**
 * lib/export/pdf.ts
 * PDF report builder — jsPDF + jspdf-autotable, lazy-loaded client-side.
 *
 * Interfaces and DEFAULT_PDF_SETTINGS are stable; pages import these directly.
 * Full implementation added in Phase F2.
 *
 * Design decisions: MERGED_EXPORTS_IMPLEMENTATION_PLAN.md Phase E2 / F2
 * - Library: jsPDF + jspdf-autotable (client-side lazy-loaded, ~250KB)
 * - Settings stored as JSONB in organizations.pdf_settings
 * - Free Tournament plan: showBranding is always forced true server-side
 * - Grouping: pass `groups` for per-division page breaks
 */

/**
 * Org-level PDF template settings — persisted in organizations.pdf_settings JSONB.
 * Loaded at export time; falls back to DEFAULT_PDF_SETTINGS if not configured.
 */
export interface OrgPdfSettings {
  /** Organization name as it appears in the report header */
  headerLine1: string;
  /** Optional subtitle line (e.g. "2026 Tournament Season") */
  headerLine2?: string;
  /** Custom footer text (contact email, website, legal note) */
  footerText?: string;
  /** Include "Exported: {date}" stamp in footer. Default: true */
  showDateStamp: boolean;
  /** Include "Page X of Y" in footer. Default: true */
  showPageNumbers: boolean;
  /** Show FieldLogicHQ branding. Force-on for free Tournament plan. Default: true */
  showBranding: boolean;
  /** Page orientation. Default: 'portrait' */
  orientation: 'portrait' | 'landscape';
  /** Header row background colour as hex (#rrggbb). Default: '#1e293b' */
  accentColor: string;
  /** Base64-encoded org logo for PDF header (data URL) */
  logoDataUrl?: string;
  /** Row density. Default: 'readable' */
  reportDensity: 'compact' | 'readable';
  /** Include guardian email/phone columns. Default: true */
  includeGuardianContacts: boolean;
  /** Include player-level notes columns. Default: true */
  includePlayerNotes: boolean;
  /** Include internal admin notes. Default: false — never shown to families */
  includeInternalNotes: boolean;
}

export const DEFAULT_PDF_SETTINGS: OrgPdfSettings = {
  headerLine1:            '',
  headerLine2:            undefined,
  footerText:             undefined,
  showDateStamp:          true,
  showPageNumbers:        true,
  showBranding:           true,
  orientation:            'portrait',
  accentColor:            '#1e293b',
  logoDataUrl:            undefined,
  reportDensity:          'readable',
  includeGuardianContacts: true,
  includePlayerNotes:     true,
  includeInternalNotes:   false,
};

// ── Internal helpers ──────────────────────────────────────────────────────────

/** Parse a hex string to { r, g, b } 0-255 values for jsPDF setFillColor. */
function hexToRgb(hex: string): { r: number; g: number; b: number } {
  const clean = hex.replace('#', '');
  const full = clean.length === 3
    ? clean.split('').map(c => c + c).join('')
    : clean;
  const r = parseInt(full.slice(0, 2), 16) || 0;
  const g = parseInt(full.slice(2, 4), 16) || 0;
  const b = parseInt(full.slice(4, 6), 16) || 0;
  return { r, g, b };
}

/** Determine if a hex colour is "dark" (and therefore needs white text). */
function isDark(hex: string): boolean {
  const { r, g, b } = hexToRgb(hex);
  // Perceived luminance formula
  return (0.299 * r + 0.587 * g + 0.114 * b) < 140;
}

const BRANDING_TEXT = 'Generated by FieldLogicHQ';
const MARGIN = 14; // mm left/right margin

/**
 * Build a jsPDF document from structured data + org PDF settings.
 * Returns the jsPDF instance (caller calls .save(filename) or .output()).
 *
 * @param jsPDFClass - The jsPDF constructor (passed in from the lazy-load caller)
 * @param autoTable  - The autoTable function (passed in from the lazy-load caller)
 * @param options    - Report content and settings
 */
export function buildTablePDF(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  jsPDFClass: any,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  autoTable: any,
  options: {
    title: string;
    subtitle?: string;
    headers: string[];
    rows: (string | number | null | undefined)[][];
    settings: OrgPdfSettings;
    /** When provided, renders one autoTable per group (division page breaks). */
    groups?: { label: string; rows: (string | number | null | undefined)[][] }[];
  },
// eslint-disable-next-line @typescript-eslint/no-explicit-any
): any {
  const { title, subtitle, headers, rows, settings, groups } = options;
  const orientation = settings.orientation === 'landscape' ? 'landscape' : 'portrait';
  const accentRgb = hexToRgb(settings.accentColor);
  const headerTextColor = isDark(settings.accentColor) ? [255, 255, 255] : [15, 15, 20];

  // ── Table body styles based on density ──────────────────────────────────
  const cellPadding = settings.reportDensity === 'compact'
    ? { top: 2, right: 4, bottom: 2, left: 4 }
    : { top: 4, right: 6, bottom: 4, left: 6 };
  const fontSize = settings.reportDensity === 'compact' ? 8 : 9;

  const doc = new jsPDFClass({ orientation, unit: 'mm', format: 'letter' });
  const pageWidth  = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const contentWidth = pageWidth - MARGIN * 2;

  // ── Accent bar helper ────────────────────────────────────────────────────
  function drawAccentBar(y: number, barH = 10) {
    doc.setFillColor(accentRgb.r, accentRgb.g, accentRgb.b);
    doc.rect(0, y, pageWidth, barH, 'F');
  }

  // ── Header block ─────────────────────────────────────────────────────────
  function drawHeader(isFirstPage: boolean) {
    let y = MARGIN;

    // Accent bar at very top
    drawAccentBar(0, 8);

    // Logo
    const logoH = 12;
    const logoW = 24;
    if (settings.logoDataUrl) {
      try {
        // Detect format from data URL prefix
        const fmt = settings.logoDataUrl.startsWith('data:image/png') ? 'PNG' : 'JPEG';
        doc.addImage(settings.logoDataUrl, fmt, MARGIN, y, logoW, logoH);
      } catch {
        // Logo failed to render — skip silently
      }
    }

    // Org name
    const textX = settings.logoDataUrl ? MARGIN + logoW + 4 : MARGIN;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(20, 20, 35);
    doc.text(settings.headerLine1 || title, textX, y + 6);

    if (settings.headerLine2) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(80, 80, 100);
      doc.text(settings.headerLine2, textX, y + 11);
    }

    y += Math.max(logoH, settings.headerLine2 ? 15 : 12);

    // Divider
    doc.setDrawColor(210, 210, 220);
    doc.setLineWidth(0.3);
    doc.line(MARGIN, y, pageWidth - MARGIN, y);
    y += 4;

    // Report title (only on first page)
    if (isFirstPage) {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.setTextColor(20, 20, 35);
      doc.text(title, MARGIN, y + 5);
      if (subtitle) {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9);
        doc.setTextColor(90, 90, 110);
        doc.text(subtitle, MARGIN, y + 10);
        y += 14;
      } else {
        y += 8;
      }
    }

    return y; // return where content begins
  }

  // ── Footer renderer (called per page by autoTable) ───────────────────────
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  function didDrawPage(data: any) {
    const footerY = pageHeight - 8;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(140, 140, 155);

    const parts: string[] = [];
    if (settings.footerText) parts.push(settings.footerText);
    if (settings.showDateStamp) {
      parts.push(`Exported: ${new Date().toISOString().split('T')[0]}`);
    }
    if (settings.showBranding) parts.push(BRANDING_TEXT);

    if (parts.length > 0) {
      doc.text(parts.join('  ·  '), MARGIN, footerY);
    }

    if (settings.showPageNumbers) {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const pageCount = (doc.internal as any).getNumberOfPages();
      const pageNum = `Page ${data.pageNumber} of ${pageCount}`;
      doc.text(pageNum, pageWidth - MARGIN, footerY, { align: 'right' });
    }
  }

  // ── Shared autoTable options ──────────────────────────────────────────────
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  function tableStyles(): Record<string, any> {
    return {
      theme: 'plain',
      styles: {
        font: 'helvetica',
        fontSize,
        cellPadding,
        overflow: 'linebreak',
        textColor: [20, 20, 35],
      },
      headStyles: {
        fillColor: [accentRgb.r, accentRgb.g, accentRgb.b],
        textColor: headerTextColor,
        fontStyle: 'bold',
        fontSize: fontSize + 0.5,
      },
      alternateRowStyles: {
        fillColor: [248, 248, 252],
      },
      columnStyles: {},
      tableWidth: 'auto',
      margin: { left: MARGIN, right: MARGIN },
      tableLineColor: [220, 220, 230],
      tableLineWidth: 0.2,
    };
  }

  // ── Render: grouped mode ─────────────────────────────────────────────────
  if (groups && groups.length > 0) {
    let startY = drawHeader(true);
    const footerMargin = 18; // leave room for footer

    groups.forEach((group, idx) => {
      // Section label
      if (idx > 0) {
        // Check if there's enough room; if not, add a page
        if (startY > pageHeight - footerMargin - 30) {
          doc.addPage();
          startY = drawHeader(false);
        }
      }

      // Group heading
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(20, 20, 35);
      doc.text(group.label, MARGIN, startY + 4);
      doc.setDrawColor(accentRgb.r, accentRgb.g, accentRgb.b);
      doc.setLineWidth(0.5);
      doc.line(MARGIN, startY + 6, pageWidth - MARGIN, startY + 6);
      startY += 10;

      // Table for this group
      autoTable(doc, {
        ...tableStyles(),
        head: [headers],
        body: group.rows.map(r => r.map(c => c ?? '')),
        startY,
        didDrawPage,
        // After drawing, update startY for next group
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        didDrawCell: undefined,
      });

      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      startY = (doc as any).lastAutoTable.finalY + 8;
    });
  } else {
    // ── Render: flat mode ──────────────────────────────────────────────────
    const startY = drawHeader(true);
    autoTable(doc, {
      ...tableStyles(),
      head: [headers],
      body: rows.map(r => r.map(c => c ?? '')),
      startY,
      didDrawPage,
    });
  }

  return doc;
}

/**
 * Full implementation: build and save a PDF from table data + org settings.
 * Lazy-loads jsPDF and jspdf-autotable to keep the initial bundle small.
 *
 * @param filename - Full filename including .pdf extension
 * @param title    - Report title shown in the document header
 * @param subtitle - Optional subtitle shown below the title
 * @param headers  - Column header labels
 * @param rows     - Data rows (used when groups is absent)
 * @param settings - Org PDF settings (falls back to DEFAULT_PDF_SETTINGS)
 * @param groups   - Optional grouped rows (one table per group with a section label)
 */
export async function downloadPDF(
  filename: string,
  title: string,
  subtitle: string | undefined,
  headers: string[],
  rows: (string | number | null | undefined)[][],
  settings: OrgPdfSettings = DEFAULT_PDF_SETTINGS,
  groups?: { label: string; rows: (string | number | null | undefined)[][] }[],
): Promise<void> {
  const [{ default: jsPDF }, { default: autoTable }] = await Promise.all([
    import('jspdf'),
    import('jspdf-autotable'),
  ]);

  const doc = buildTablePDF(jsPDF, autoTable, { title, subtitle, headers, rows, settings, groups });
  doc.save(filename);
}

// ════════════════════════════════════════════════════════════════════════════
//  Dugout-wall lineup posters (Coach Lineup Builder Phase 3)
//  A high-contrast, pen-fillable poster — NOT the generic report table. Blank
//  cells print as empty boxes the coach fills in by hand at the field; an
//  explicitly-benched cell prints "BN". Drawn with jsPDF primitives for exact
//  control over fixed row heights, thick grid lines, and empty boxes.
// ════════════════════════════════════════════════════════════════════════════

/** Bench sentinel stored in a lineup cell (matches lib/lineup-analysis BENCH_POSITION). */
const POSTER_BENCH = 'Bench';
const POSTER_MARGIN = 13; // mm — a touch tighter than reports to win grid width

/** Full-name labels for diamond position codes, used in the poster legend. Driven by the
 *  Sport Pack's `positions` for *which* codes appear; this only supplies human names.
 *  A future non-diamond sport would supply its own labels (codes fall back to themselves). */
const DIAMOND_POSITION_LABELS: Record<string, string> = {
  P: 'Pitcher', C: 'Catcher', '1B': 'First base', '2B': 'Second base', '3B': 'Third base',
  SS: 'Shortstop', LF: 'Left field', CF: 'Center field', RF: 'Right field',
  OF: 'Outfield', DH: 'Designated hitter', EH: 'Extra hitter',
};

/** Build the `{ code, label }[]` legend from a Sport Pack's position codes. */
export function buildPositionLegend(codes: string[]): { code: string; label: string }[] {
  return codes.map(code => ({ code, label: DIAMOND_POSITION_LABELS[code] ?? code }));
}

export interface LineupPosterPlayer {
  /** Batting slot number as a string ('' for a 9-player-mode bench/sub with no slot). */
  battingOrder: string;
  /** Display name, e.g. "#12 Jane Smith". */
  name: string;
  /** True for a 9-player-mode non-starter (rendered after the order, tagged "sub"). */
  isSub: boolean;
  /** inning(string) → position code. '' = blank (prints an empty box); 'Bench' = sit. */
  inningPositions: Record<string, string>;
}

export interface LineupPosterOptions {
  teamName: string;
  opponent?: string | null;
  /** Drives the matchup separator: 'away' → "@", everything else → "vs". */
  homeAway?: 'home' | 'away' | 'neutral' | null;
  /** Pre-formatted date/time line, e.g. "Sat, Jun 28, 2026 · 10:00 a.m." */
  dateLabel: string;
  /** Shown on the batting-order card (not the poster). */
  eventName?: string;
  inningCount: number;
  players: LineupPosterPlayer[];
  legend: { code: string; label: string }[];
  /** When set, the coach's lineup notes print at the foot of the poster (e.g. opponent scouting). */
  includeNotes?: boolean;
  notes?: string | null;
  /** Header accent colour (org PDF accent); text auto-contrasts. */
  accentColor: string;
  showBranding: boolean;
}

/** Matchup separator: away games read "@ Opponent", home/neutral read "vs Opponent". */
function matchupSeparator(homeAway?: 'home' | 'away' | 'neutral' | null): string {
  return homeAway === 'away' ? '@' : 'vs';
}

const clampNum = (n: number, lo: number, hi: number) => Math.max(lo, Math.min(hi, n));

/** Shorten text to fit a max width in the current font, adding an ellipsis. */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function fitText(doc: any, text: string, maxW: number): string {
  if (doc.getTextWidth(text) <= maxW) return text;
  let t = text;
  while (t.length > 1 && doc.getTextWidth(t + '…') > maxW) t = t.slice(0, -1);
  return t + '…';
}

/**
 * Build the dugout-wall poster (landscape): team/opponent/date header, a
 * batting-order × innings grid with empty boxes for blank cells, and a position
 * legend along the bottom. Returns the jsPDF doc (caller saves it).
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function buildLineupPosterDoc(jsPDFClass: any, opts: LineupPosterOptions): any {
  const doc = new jsPDFClass({ orientation: 'landscape', unit: 'mm', format: 'letter' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const M = POSTER_MARGIN;
  const accent = hexToRgb(opts.accentColor || '#1e293b');
  const headText = isDark(opts.accentColor || '#1e293b') ? [255, 255, 255] : [20, 20, 30];

  // ── Header band ───────────────────────────────────────────────────────────
  doc.setFillColor(accent.r, accent.g, accent.b);
  doc.rect(0, 0, pageW, 4, 'F');

  let y = 15;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(15, 15, 25);
  const title = opts.opponent
    ? `${opts.teamName}   ${matchupSeparator(opts.homeAway)}   ${opts.opponent}`
    : opts.teamName;
  doc.text(fitText(doc, title, pageW - 2 * M - 60), M, y);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(70, 70, 90);
  doc.text(opts.dateLabel, pageW - M, y, { align: 'right' });

  y += 5;
  doc.setDrawColor(accent.r, accent.g, accent.b);
  doc.setLineWidth(0.6);
  doc.line(M, y, pageW - M, y);

  // ── Optional coach notes (printed at the foot) — measured first so the grid reserves room ──
  const notesText = opts.includeNotes && opts.notes ? opts.notes.trim() : '';
  let notesLines: string[] = [];
  if (notesText) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    notesLines = doc.splitTextToSize(notesText, pageW - 2 * M);
    if (notesLines.length > 6) {
      notesLines = notesLines.slice(0, 6);
      notesLines[5] = fitText(doc, `${notesLines[5]} …`, pageW - 2 * M);
    }
  }
  const notesReserve = notesLines.length ? notesLines.length * 4 + 7 : 0;

  // ── Grid geometry ─────────────────────────────────────────────────────────
  const gridTop = y + 5;
  const legendReserve = 18 + notesReserve; // legend + branding (+ optional notes) below the grid
  const gridBottom = pageH - M - legendReserve;
  const gridArea = gridBottom - gridTop;

  const inningCount = Math.max(1, opts.inningCount); // defensive: UI constrains to 1–12
  const colNumW = 13;
  const colNameW = 56;
  const innW = (pageW - 2 * M - colNumW - colNameW) / inningCount;
  const totalW = pageW - 2 * M;
  const headerRowH = 9;
  const n = Math.max(1, opts.players.length);
  const bodyRowH = clampNum((gridArea - headerRowH) / n, 6, 13);
  const gridEnd = gridTop + headerRowH + bodyRowH * opts.players.length;

  const colNameX = M + colNumW;
  const innX = (i: number) => M + colNumW + colNameW + innW * i; // left of inning i (0-based)

  // ── Header row ────────────────────────────────────────────────────────────
  doc.setFillColor(accent.r, accent.g, accent.b);
  doc.rect(M, gridTop, totalW, headerRowH, 'F');
  doc.setTextColor(headText[0], headText[1], headText[2]);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9.5);
  const hMid = gridTop + headerRowH / 2;
  doc.text('#', M + colNumW / 2, hMid, { align: 'center', baseline: 'middle' });
  doc.text('Batter', colNameX + 3, hMid, { align: 'left', baseline: 'middle' });
  for (let i = 0; i < inningCount; i++) {
    doc.text(String(i + 1), innX(i) + innW / 2, hMid, { align: 'center', baseline: 'middle' });
  }

  // ── Body: zebra fills + text ──────────────────────────────────────────────
  opts.players.forEach((p, k) => {
    const top = gridTop + headerRowH + k * bodyRowH;
    const mid = top + bodyRowH / 2;
    if (k % 2 === 1) {
      doc.setFillColor(247, 247, 250);
      doc.rect(M, top, totalW, bodyRowH, 'F');
    }
    // batting number
    if (p.battingOrder) {
      doc.setTextColor(20, 20, 30);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.text(p.battingOrder, M + colNumW / 2, mid, { align: 'center', baseline: 'middle' });
    }
    // name
    doc.setFont('helvetica', p.isSub ? 'normal' : 'bold');
    doc.setFontSize(10);
    doc.setTextColor(p.isSub ? 90 : 20, p.isSub ? 90 : 20, p.isSub ? 110 : 30);
    const nm = p.isSub ? `${p.name}  (sub)` : p.name;
    doc.text(fitText(doc, nm, colNameW - 5), colNameX + 3, mid, { align: 'left', baseline: 'middle' });
    // innings — blank stays an empty box; Bench → "BN"
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(25, 25, 35);
    for (let i = 0; i < inningCount; i++) {
      const raw = p.inningPositions[String(i + 1)] || '';
      if (!raw) continue;
      const label = raw === POSTER_BENCH ? 'BN' : raw;
      if (raw === POSTER_BENCH) doc.setTextColor(150, 150, 165);
      doc.text(label, innX(i) + innW / 2, mid, { align: 'center', baseline: 'middle' });
      if (raw === POSTER_BENCH) doc.setTextColor(25, 25, 35);
    }
  });

  // ── Grid lines (drawn over fills/text; thin enough not to obscure) ─────────
  doc.setDrawColor(30, 30, 40);
  // horizontal: top, header/body split, each body row, bottom
  const hLines: number[] = [gridTop, gridTop + headerRowH];
  for (let k = 1; k <= opts.players.length; k++) hLines.push(gridTop + headerRowH + k * bodyRowH);
  hLines.forEach((ly, idx) => {
    doc.setLineWidth(idx === 0 || idx === hLines.length - 1 ? 0.8 : 0.3);
    doc.line(M, ly, M + totalW, ly);
  });
  // vertical: outer + structural separators (after #, after Batter) + inning dividers
  for (let i = 0; i <= inningCount; i++) {
    const vx = innX(i);
    doc.setLineWidth(i === inningCount ? 0.8 : 0.3);
    doc.line(vx, gridTop, vx, gridEnd);
  }
  doc.setLineWidth(0.8); doc.line(M, gridTop, M, gridEnd);              // left edge
  doc.setLineWidth(0.6); doc.line(colNameX, gridTop, colNameX, gridEnd); // after #
  doc.line(colNameX + colNameW, gridTop, colNameX + colNameW, gridEnd);  // after Batter

  // ── Legend (kept above any notes block) ────────────────────────────────────
  const legendY = clampNum(gridEnd + 6, gridTop, pageH - M - 8 - notesReserve);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(80, 80, 100);
  const parts = opts.legend.map(l => `${l.code} ${l.label}`);
  parts.push('BN Bench');
  const legendStr = `Positions:   ${parts.join('     ')}     ·     Blank box = fill in at the field`;
  const lines = doc.splitTextToSize(legendStr, totalW);
  doc.text(lines, M, legendY);

  // ── Optional coach notes block (bottom-anchored, e.g. opponent scouting) ────
  if (notesLines.length) {
    const notesTop = pageH - M - notesReserve + 4;
    doc.setDrawColor(210, 210, 220);
    doc.setLineWidth(0.3);
    doc.line(M, notesTop - 3, M + totalW, notesTop - 3);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(90, 90, 110);
    doc.text('NOTES', M, notesTop);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(40, 40, 55);
    doc.text(notesLines, M, notesTop + 4.5);
  }

  if (opts.showBranding) {
    doc.setFontSize(7);
    doc.setTextColor(150, 150, 165);
    doc.text('Generated by FieldLogicHQ', pageW - M, pageH - 5, { align: 'right' });
  }

  return doc;
}

/**
 * Build the stripped batting-order card (portrait): team/opponent/date and a
 * large-type batting order for the scorekeeper / dugout. Subs listed at the foot.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function buildBattingOrderCardDoc(jsPDFClass: any, opts: LineupPosterOptions): any {
  const doc = new jsPDFClass({ orientation: 'portrait', unit: 'mm', format: 'letter' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const M = 18;
  const accent = hexToRgb(opts.accentColor || '#1e293b');

  doc.setFillColor(accent.r, accent.g, accent.b);
  doc.rect(0, 0, pageW, 5, 'F');

  let y = 20;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(15, 15, 25);
  const title = opts.opponent
    ? `${opts.teamName} ${matchupSeparator(opts.homeAway)} ${opts.opponent}`
    : opts.teamName;
  doc.text(fitText(doc, title, pageW - 2 * M), pageW / 2, y, { align: 'center' });

  y += 7;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(90, 90, 110);
  doc.text([opts.dateLabel, opts.eventName].filter(Boolean).join('  ·  '), pageW / 2, y, { align: 'center' });

  y += 9;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(accent.r, accent.g, accent.b);
  doc.text('BATTING ORDER', pageW / 2, y, { align: 'center' });
  y += 4;
  doc.setDrawColor(accent.r, accent.g, accent.b);
  doc.setLineWidth(0.6);
  doc.line(M, y, pageW - M, y);

  const batters = opts.players.filter(p => p.battingOrder);
  const subs = opts.players.filter(p => p.isSub || !p.battingOrder);

  const listTop = y + 6;
  const listBottom = pageH - M - (subs.length ? 22 : 10);
  const rowH = clampNum((listBottom - listTop) / Math.max(1, batters.length), 9, 18);

  batters.forEach((p, k) => {
    const top = listTop + k * rowH;
    const mid = top + rowH / 2;
    if (k % 2 === 1) {
      doc.setFillColor(247, 247, 250);
      doc.rect(M, top, pageW - 2 * M, rowH, 'F');
    }
    doc.setTextColor(accent.r, accent.g, accent.b);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.text(p.battingOrder, M + 4, mid, { align: 'left', baseline: 'middle' });
    doc.setTextColor(20, 20, 30);
    doc.setFontSize(15);
    doc.text(fitText(doc, p.name, pageW - 2 * M - 24), M + 18, mid, { align: 'left', baseline: 'middle' });
    doc.setDrawColor(225, 225, 232);
    doc.setLineWidth(0.2);
    doc.line(M, top + rowH, pageW - M, top + rowH);
  });

  if (subs.length) {
    const sy = pageH - M - 14;
    doc.setDrawColor(accent.r, accent.g, accent.b);
    doc.setLineWidth(0.4);
    doc.line(M, sy, pageW - M, sy);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(90, 90, 110);
    doc.text('Subs', M, sy + 6);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(40, 40, 55);
    doc.text(fitText(doc, subs.map(s => s.name).join(',  '), pageW - 2 * M - 18), M + 16, sy + 6);
  }

  if (opts.showBranding) {
    doc.setFontSize(7);
    doc.setTextColor(150, 150, 165);
    doc.text('Generated by FieldLogicHQ', pageW - M, pageH - 6, { align: 'right' });
  }

  return doc;
}

/** Lazy-load jsPDF and save the dugout-wall positions-by-inning poster. */
export async function downloadLineupPoster(filename: string, opts: LineupPosterOptions): Promise<void> {
  const { default: jsPDF } = await import('jspdf');
  buildLineupPosterDoc(jsPDF, opts).save(filename);
}

/** Lazy-load jsPDF and save the stripped batting-order card. */
export async function downloadBattingOrderCard(filename: string, opts: LineupPosterOptions): Promise<void> {
  const { default: jsPDF } = await import('jspdf');
  buildBattingOrderCardDoc(jsPDF, opts).save(filename);
}
