/**
 * lib/export/pdf.ts
 * PDF report builder — jsPDF + jspdf-autotable, lazy-loaded client-side.
 *
 * Interfaces and DEFAULT_PDF_SETTINGS are stable; pages import these directly.
 * Full implementation added in Phase F2.
 *
 * Design decisions: MERGED_EXPORTS_IMPLEMENTATION_PLAN.md Phase E2 / F2
 * - Library: jsPDF + jspdf-autotable (client-side lazy-loaded, ~250KB)
 * - Settings stored as JSONB in organizations.pdf_settings
 * - Free Tournament plan: showBranding is always forced true server-side
 * - Grouping: pass `groups` for per-division page breaks
 */

/**
 * Org-level PDF template settings — persisted in organizations.pdf_settings JSONB.
 * Loaded at export time; falls back to DEFAULT_PDF_SETTINGS if not configured.
 */
export interface OrgPdfSettings {
  /** Organization name as it appears in the report header */
  headerLine1: string;
  /** Optional subtitle line (e.g. "2026 Tournament Season") */
  headerLine2?: string;
  /** Custom footer text (contact email, website, legal note) */
  footerText?: string;
  /** Include "Exported: {date}" stamp in footer. Default: true */
  showDateStamp: boolean;
  /** Include "Page X of Y" in footer. Default: true */
  showPageNumbers: boolean;
  /** Show FieldLogicHQ branding. Force-on for free Tournament plan. Default: true */
  showBranding: boolean;
  /** Page orientation. Default: 'portrait' */
  orientation: 'portrait' | 'landscape';
  /** Header row background colour as hex (#rrggbb). Default: '#1e293b' */
  accentColor: string;
  /** Base64-encoded org logo for PDF header (data URL) */
  logoDataUrl?: string;
  /** Row density. Default: 'readable' */
  reportDensity: 'compact' | 'readable';
  /** Include guardian email/phone columns. Default: true */
  includeGuardianContacts: boolean;
  /** Include player-level notes columns. Default: true */
  includePlayerNotes: boolean;
  /** Include internal admin notes. Default: false — never shown to families */
  includeInternalNotes: boolean;
}

export const DEFAULT_PDF_SETTINGS: OrgPdfSettings = {
  headerLine1:            '',
  headerLine2:            undefined,
  footerText:             undefined,
  showDateStamp:          true,
  showPageNumbers:        true,
  showBranding:           true,
  orientation:            'portrait',
  accentColor:            '#1e293b',
  logoDataUrl:            undefined,
  reportDensity:          'readable',
  includeGuardianContacts: true,
  includePlayerNotes:     true,
  includeInternalNotes:   false,
};

// ── Internal helpers ──────────────────────────────────────────────────────────

/** Parse a hex string to { r, g, b } 0-255 values for jsPDF setFillColor. */
function hexToRgb(hex: string): { r: number; g: number; b: number } {
  const clean = hex.replace('#', '');
  const full = clean.length === 3
    ? clean.split('').map(c => c + c).join('')
    : clean;
  const r = parseInt(full.slice(0, 2), 16) || 0;
  const g = parseInt(full.slice(2, 4), 16) || 0;
  const b = parseInt(full.slice(4, 6), 16) || 0;
  return { r, g, b };
}

/** Determine if a hex colour is "dark" (and therefore needs white text). */
function isDark(hex: string): boolean {
  const { r, g, b } = hexToRgb(hex);
  // Perceived luminance formula
  return (0.299 * r + 0.587 * g + 0.114 * b) < 140;
}

const BRANDING_TEXT = 'Generated by FieldLogicHQ';
const MARGIN = 14; // mm left/right margin

/**
 * Build a jsPDF document from structured data + org PDF settings.
 * Returns the jsPDF instance (caller calls .save(filename) or .output()).
 *
 * @param jsPDFClass - The jsPDF constructor (passed in from the lazy-load caller)
 * @param autoTable  - The autoTable function (passed in from the lazy-load caller)
 * @param options    - Report content and settings
 */
export function buildTablePDF(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  jsPDFClass: any,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  autoTable: any,
  options: {
    title: string;
    subtitle?: string;
    headers: string[];
    rows: (string | number | null | undefined)[][];
    settings: OrgPdfSettings;
    /** When provided, renders one autoTable per group (division page breaks). */
    groups?: { label: string; rows: (string | number | null | undefined)[][] }[];
  },
// eslint-disable-next-line @typescript-eslint/no-explicit-any
): any {
  const { title, subtitle, headers, rows, settings, groups } = options;
  const orientation = settings.orientation === 'landscape' ? 'landscape' : 'portrait';
  const accentRgb = hexToRgb(settings.accentColor);
  const headerTextColor = isDark(settings.accentColor) ? [255, 255, 255] : [15, 15, 20];

  // ── Table body styles based on density ──────────────────────────────────
  const cellPadding = settings.reportDensity === 'compact'
    ? { top: 2, right: 4, bottom: 2, left: 4 }
    : { top: 4, right: 6, bottom: 4, left: 6 };
  const fontSize = settings.reportDensity === 'compact' ? 8 : 9;

  const doc = new jsPDFClass({ orientation, unit: 'mm', format: 'letter' });
  const pageWidth  = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const contentWidth = pageWidth - MARGIN * 2;

  // ── Accent bar helper ────────────────────────────────────────────────────
  function drawAccentBar(y: number, barH = 10) {
    doc.setFillColor(accentRgb.r, accentRgb.g, accentRgb.b);
    doc.rect(0, y, pageWidth, barH, 'F');
  }

  // ── Header block ─────────────────────────────────────────────────────────
  function drawHeader(isFirstPage: boolean) {
    let y = MARGIN;

    // Accent bar at very top
    drawAccentBar(0, 8);

    // Logo
    const logoH = 12;
    const logoW = 24;
    if (settings.logoDataUrl) {
      try {
        // Detect format from data URL prefix
        const fmt = settings.logoDataUrl.startsWith('data:image/png') ? 'PNG' : 'JPEG';
        doc.addImage(settings.logoDataUrl, fmt, MARGIN, y, logoW, logoH);
      } catch {
        // Logo failed to render — skip silently
      }
    }

    // Org name
    const textX = settings.logoDataUrl ? MARGIN + logoW + 4 : MARGIN;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(20, 20, 35);
    doc.text(settings.headerLine1 || title, textX, y + 6);

    if (settings.headerLine2) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(80, 80, 100);
      doc.text(settings.headerLine2, textX, y + 11);
    }

    y += Math.max(logoH, settings.headerLine2 ? 15 : 12);

    // Divider
    doc.setDrawColor(210, 210, 220);
    doc.setLineWidth(0.3);
    doc.line(MARGIN, y, pageWidth - MARGIN, y);
    y += 4;

    // Report title (only on first page)
    if (isFirstPage) {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.setTextColor(20, 20, 35);
      doc.text(title, MARGIN, y + 5);
      if (subtitle) {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9);
        doc.setTextColor(90, 90, 110);
        doc.text(subtitle, MARGIN, y + 10);
        y += 14;
      } else {
        y += 8;
      }
    }

    return y; // return where content begins
  }

  // ── Footer renderer (called per page by autoTable) ───────────────────────
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  function didDrawPage(data: any) {
    const footerY = pageHeight - 8;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(140, 140, 155);

    const parts: string[] = [];
    if (settings.footerText) parts.push(settings.footerText);
    if (settings.showDateStamp) {
      parts.push(`Exported: ${new Date().toISOString().split('T')[0]}`);
    }
    if (settings.showBranding) parts.push(BRANDING_TEXT);

    if (parts.length > 0) {
      doc.text(parts.join('  ·  '), MARGIN, footerY);
    }

    if (settings.showPageNumbers) {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const pageCount = (doc.internal as any).getNumberOfPages();
      const pageNum = `Page ${data.pageNumber} of ${pageCount}`;
      doc.text(pageNum, pageWidth - MARGIN, footerY, { align: 'right' });
    }
  }

  // ── Shared autoTable options ──────────────────────────────────────────────
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  function tableStyles(): Record<string, any> {
    return {
      theme: 'plain',
      styles: {
        font: 'helvetica',
        fontSize,
        cellPadding,
        overflow: 'linebreak',
        textColor: [20, 20, 35],
      },
      headStyles: {
        fillColor: [accentRgb.r, accentRgb.g, accentRgb.b],
        textColor: headerTextColor,
        fontStyle: 'bold',
        fontSize: fontSize + 0.5,
      },
      alternateRowStyles: {
        fillColor: [248, 248, 252],
      },
      columnStyles: {},
      tableWidth: 'auto',
      margin: { left: MARGIN, right: MARGIN },
      tableLineColor: [220, 220, 230],
      tableLineWidth: 0.2,
    };
  }

  // ── Render: grouped mode ─────────────────────────────────────────────────
  if (groups && groups.length > 0) {
    let startY = drawHeader(true);
    const footerMargin = 18; // leave room for footer

    groups.forEach((group, idx) => {
      // Section label
      if (idx > 0) {
        // Check if there's enough room; if not, add a page
        if (startY > pageHeight - footerMargin - 30) {
          doc.addPage();
          startY = drawHeader(false);
        }
      }

      // Group heading
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(20, 20, 35);
      doc.text(group.label, MARGIN, startY + 4);
      doc.setDrawColor(accentRgb.r, accentRgb.g, accentRgb.b);
      doc.setLineWidth(0.5);
      doc.line(MARGIN, startY + 6, pageWidth - MARGIN, startY + 6);
      startY += 10;

      // Table for this group
      autoTable(doc, {
        ...tableStyles(),
        head: [headers],
        body: group.rows.map(r => r.map(c => c ?? '')),
        startY,
        didDrawPage,
        // After drawing, update startY for next group
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        didDrawCell: undefined,
      });

      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      startY = (doc as any).lastAutoTable.finalY + 8;
    });
  } else {
    // ── Render: flat mode ──────────────────────────────────────────────────
    const startY = drawHeader(true);
    autoTable(doc, {
      ...tableStyles(),
      head: [headers],
      body: rows.map(r => r.map(c => c ?? '')),
      startY,
      didDrawPage,
    });
  }

  return doc;
}

/**
 * Full implementation: build and save a PDF from table data + org settings.
 * Lazy-loads jsPDF and jspdf-autotable to keep the initial bundle small.
 *
 * @param filename - Full filename including .pdf extension
 * @param title    - Report title shown in the document header
 * @param subtitle - Optional subtitle shown below the title
 * @param headers  - Column header labels
 * @param rows     - Data rows (used when groups is absent)
 * @param settings - Org PDF settings (falls back to DEFAULT_PDF_SETTINGS)
 * @param groups   - Optional grouped rows (one table per group with a section label)
 */
export async function downloadPDF(
  filename: string,
  title: string,
  subtitle: string | undefined,
  headers: string[],
  rows: (string | number | null | undefined)[][],
  settings: OrgPdfSettings = DEFAULT_PDF_SETTINGS,
  groups?: { label: string; rows: (string | number | null | undefined)[][] }[],
): Promise<void> {
  const [{ default: jsPDF }, { default: autoTable }] = await Promise.all([
    import('jspdf'),
    import('jspdf-autotable'),
  ]);

  const doc = buildTablePDF(jsPDF, autoTable, { title, subtitle, headers, rows, settings, groups });
  doc.save(filename);
}
