/**
 * THE BUDGET-VS-ACTUAL FILES — one per shape, each labelled with the basis it was cut on.
 *
 * Two defects found in the §145 walk live here, and both are the invisible kind:
 *
 *  1. **By activity had no export.** It fell through to the statement — never a decision, just what
 *     was left when the view was not Months — so the one shape that answers "did the tournament pay
 *     for itself?" produced a file that could not answer it.
 *  2. **A To date file was labelled as a whole season.** The figures were re-cut correctly and both
 *     LABELS were left behind: a part-year plan came out headed "Budgeted" under a row called
 *     "Season net". Right numbers, wrong name — which is worse than wrong numbers, because a board
 *     reading the attachment has nothing to check it against.
 */
import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import {
  bvaExportColumns, bvaCategoryRows, bvaActivityRows,
} from '../../lib/coach-money-exports';

const cat = (name: string, over: Record<string, unknown> = {}) => ({
  categoryId: name.toLowerCase(),
  categoryName: name,
  budgeted: 900, actual: 240, variance: 660, inPlan: true,
  items: [{
    itemName: 'Entry Fees', budgeted: 900, actual: 0, variance: 900,
    inPlan: true, lineCount: 1, refundTotal: 0, grossActual: 0,
  }],
  ...over,
});

const STATEMENT = {
  buffer: 0, unbudgeted: 0, effectiveBudget: 10700, totalActual: 4909.98, headroom: 5790.02,
  report: {
    revenue: { categories: [cat('Player dues')], budgeted: 1800, actual: 6339.35, variance: 4539.35 },
    expenses: { categories: [cat('Tournaments')] },
    net: { budgeted: -8900, actual: 1429.37, variance: 10329.37 },
  },
};

const label = (rows: { item?: unknown }[]) => rows.map(r => String(r.item ?? ''));

describe('a report is dressed; a dataset is not', () => {
  /**
   * ⚠⚠ THE GATE THIS PINS WAS A REAL DEFECT FOR ABOUT AN HOUR (/review, 2026-09-05). The branding
   * footer was added to EVERY money spreadsheet, which quietly broke the import round trip: the
   * budget plan and bills files are read back in, the parser treats every non-blank row after the
   * header as DATA, and a trailing "Generated by FieldLogicHQ" would have arrived in the import
   * preview as a budget line.
   *
   * The rule that fixed it is the one worth defending: **a masthead is what makes a file a report.**
   * Both ends of the file — the block above the table and the mark below it — hang off that one
   * flag, so they can never disagree about which kind of file this is.
   *
   * This test reads the SOURCE rather than building a workbook, because the decision lives in the
   * download path (a browser-only function that writes a Blob) and the thing worth pinning is the
   * predicate, not ExcelJS.
   */
  test('the footer is gated on the masthead, not on the format', async () => {
    const fs = await import('node:fs');
    const src = fs.readFileSync(
      new URL('../../lib/coach-money-exports.ts', import.meta.url), 'utf8');
    const line = src.split('\n').find(l => l.trim().startsWith('footer:'));
    assert.ok(line, 'the download path no longer sets a footer — did it move?');
    assert.match(
      line!, /spec\.masthead\s*&&/,
      'the branding footer must hang off the masthead: a file without one is a dataset this '
      + 'product reads back, and a trailing prose row returns as a data row');
    // And the masthead itself is only ever handed to the Excel writer — never CSV, never PDF.
    assert.ok(!/downloadCSVBlob[\s\S]{0,400}masthead/.test(src), 'CSV must start on its column row');
  });
});

describe('a file says which span it was cut on', () => {
  test('the plan column is named by the basis, in the file as on the screen', () => {
    assert.equal(bvaExportColumns('season')[1].label, 'Budgeted');
    assert.equal(bvaExportColumns('todate')[1].label, 'Plan to date');
    // The other three never move — a basis re-cuts the plan and nothing else.
    for (const basis of ['season', 'todate'] as const) {
      assert.deepEqual(
        bvaExportColumns(basis).map(c => c.key), ['item', 'budgeted', 'actual', 'variance']);
      assert.equal(bvaExportColumns(basis)[2].label, 'Actual');
    }
  });

  test('the closing row is renamed too — both shapes', () => {
    assert.ok(label(bvaCategoryRows(STATEMENT, 'season').rows).includes('Season net'));
    assert.ok(label(bvaCategoryRows(STATEMENT, 'todate').rows).includes('Net to date'));
    /* ⚠ Under To date this figure is a CASH-TIMING statement wearing a PROFITABILITY name — a team
       whose dues start in October reads deeply under water on a healthy bank balance. The screen
       renames it for exactly that reason; a file that kept the season's name would be the only
       place a reader could not tell. */
    const activity = { activities: [], buffer: 0, net: STATEMENT.report.net };
    assert.ok(label(bvaActivityRows(activity, 'season').rows).includes('Season net'));
    assert.ok(label(bvaActivityRows(activity, 'todate').rows).includes('Net to date'));
  });

  test('an un-passed basis still produces the ordinary season file', () => {
    // Every existing caller predates the parameter; none of them may change behaviour.
    assert.deepEqual(bvaCategoryRows(STATEMENT).rows, bvaCategoryRows(STATEMENT, 'season').rows);
  });
});

describe('by activity gets the shape it is named for', () => {
  const BLOCK = {
    categoryId: 'tournaments',
    categoryName: 'Tournaments',
    revenue: cat('Tournaments', {
      items: [{
        itemName: 'Concession revenue', budgeted: 0, actual: 400, variance: 400,
        inPlan: false, lineCount: 1, refundTotal: 0, grossActual: 400,
      }],
    }),
    costs: cat('Tournaments'),
    net: { budgeted: -900, actual: 160, variance: 1060 },
  };

  test('a block LEADS with its own net, then revenue, then costs', () => {
    const out = bvaActivityRows({
      activities: [BLOCK], buffer: 0, net: { budgeted: 0, actual: 0, variance: 0 },
    }, 'season', () => false);
    const rows = label(out.rows);

    /* ⚠⚠ THE FILE'S SHAPE IS THE SCREEN'S SHAPE (owner ruling 2026-09-06, QA §146 F2). The heading
       row IS the total — the figure a coach reads on screen, on the row they read it on — and there
       is no shouted band above it and no "netted" row below. This is the row the whole shape exists
       for, and the statement structurally cannot produce it: a category appears in both of its
       sections, so nothing there sets one against the other. */
    assert.equal(rows[0], 'Tournaments');
    assert.deepEqual(
      { b: out.rows[0].budgeted, a: out.rows[0].actual, v: out.rows[0].variance },
      { b: -900, a: 160, v: 1060 },
      'the heading row carries the block net, unchanged — only its position moved',
    );
    assert.ok(!rows.includes('TOURNAMENTS'), 'no shouted band over the block');
    assert.ok(!rows.some(r => /netted|Tournaments cost/.test(r)), 'no closing subtotal row');

    assert.ok(rows.includes('REVENUE') && rows.includes('COSTS'));
    assert.ok(rows.some(r => r.includes('Concession revenue')));
    assert.ok(rows.indexOf('Tournaments') < rows.indexOf('REVENUE'));
    assert.ok(rows.indexOf('REVENUE') < rows.indexOf('COSTS'));
  });

  test('the inner labels ride INSIDE the block, at the level of the lines they introduce', () => {
    const out = bvaActivityRows({
      activities: [BLOCK], buffer: 0, net: { budgeted: 0, actual: 0, variance: 0 },
    }, 'season', () => false);
    const at = (name: string) => out.kinds[label(out.rows).indexOf(name)];

    /* On screen these are the quietest thing in the table and they live behind the activity's fold.
       As `category` rows they were bold, level-0, and split one activity into two Excel groups. */
    assert.equal(at('Tournaments'), 'category', 'the activity is the group parent');
    assert.equal(at('REVENUE'), 'item');
    assert.equal(at('COSTS'), 'item');
  });

  test('a one-sided block loses the inner labels, and still nets negative', () => {
    const out = bvaActivityRows({
      activities: [{ ...BLOCK, revenue: null }], buffer: 0,
      net: { budgeted: 0, actual: 0, variance: 0 },
    }, 'season', () => false);
    const rows = label(out.rows);

    /* On a category with one half, "Revenue" and "Costs" are headings distinguishing nothing from
       nothing — the screen's rule, kept. And a cost-only block nets negative and says so, rather
       than being hidden or flipped: the FIGURE carries that now, not a "cost" suffix on the label.
       The screen prints it in brackets and the spreadsheet's own number format does the same. */
    assert.ok(!rows.includes('REVENUE') && !rows.includes('COSTS'));
    assert.equal(rows[0], 'Tournaments', 'the name alone is the label — no "cost" suffix');
    assert.ok(!rows.some(r => /netted|Tournaments cost/.test(r)));
    assert.equal(out.rows[0].budgeted, -900, 'the negative net is stated, not hidden or flipped');
  });

  test('dues lead as a ROW, never as a block', () => {
    const dues = {
      ...BLOCK, categoryId: 'dues', categoryName: 'Player dues', costs: null,
      revenue: cat('Player dues', { items: [] }),
    };
    const rows = label(bvaActivityRows({
      activities: [dues, BLOCK], buffer: 0, net: { budgeted: 0, actual: 0, variance: 0 },
    }, 'season', id => id === 'dues').rows);

    assert.equal(rows[0], 'Player dues', 'dues lead the shape, as on screen');
    /* A band, one row and a subtotal would be the words "Player dues" three times over a category
       with one figure that can never have a cost half. */
    assert.ok(!rows.includes('PLAYER DUES'));
    assert.ok(!rows.some(r => r.startsWith('Player dues netted')));
    /* ⚠ And they can never be OMITTED: both shapes close on the same Season net, and it moved when
       dues joined the revenue half — blocks without them would sum to one number under a total
       saying another. */
    assert.ok(rows.includes('Tournaments'));
  });

  test('an unset dues row says "not set yet", not "not budgeted"', () => {
    const rows = label(bvaActivityRows({
      activities: [{
        ...BLOCK, categoryId: 'dues', categoryName: 'Player dues', costs: null,
        revenue: cat('Player dues', { inPlan: false, items: [] }),
      }],
      buffer: 0, net: { budgeted: 0, actual: 0, variance: 0 },
    }, 'season', id => id === 'dues').rows);
    // A team with no schedule has not failed to budget something — it has not set its dues up.
    assert.ok(rows[0].includes('not set yet'));
    assert.ok(!rows[0].includes('not budgeted'));
  });

  test('both shapes describe one item the same way', () => {
    const withBack = cat('Team Gear', {
      items: [{
        itemName: 'Jerseys', budgeted: 500, actual: 609.98, variance: -109.98,
        inPlan: true, lineCount: 1, refundTotal: 150, grossActual: 759.98,
      }],
    });
    const fromStatement = label(bvaCategoryRows({
      ...STATEMENT,
      report: { ...STATEMENT.report, expenses: { categories: [withBack] } },
    }).rows).find(r => r.includes('Jerseys'));
    const fromActivity = label(bvaActivityRows({
      activities: [{
        categoryId: 'gear', categoryName: 'Team Gear', revenue: null, costs: withBack,
        net: { budgeted: 500, actual: 609.98, variance: -109.98 },
      }],
      buffer: 0, net: { budgeted: 0, actual: 0, variance: 0 },
    }, 'season', () => false).rows).find(r => r.includes('Jerseys'));

    /* Money back is said in the LABEL, not given a row — a second row would make the column add up
       to more spending than the team did. Both files have to say it the same way, which is why the
       two shapes share one item builder. */
    assert.equal(fromStatement, fromActivity);
    assert.ok(fromStatement?.includes('less 150.00 back'));
  });
});
