import assert from 'node:assert/strict';
import { describe, it } from 'node:test';
import { parseCSV } from '../../lib/import/csv.ts';
import { ImportParseError } from '../../lib/import/types.ts';

describe('tabular import parsing', () => {
  it('skips blank leading rows and blank records while preserving source row numbers', () => {
    const parsed = parseCSV('\r\nTeam Name,Division Name,Status\n,,\nBlue Jays,U11,accepted\n  , , \nRed Hawks,U11,pending', 10);

    assert.deepEqual(parsed.headers, ['Team Name', 'Division Name', 'Status']);
    assert.deepEqual(parsed.rows.map(row => row.rowNumber), [4, 6]);
    assert.equal(parsed.rows[0].values['Team Name'], 'Blue Jays');
    assert.equal(parsed.rows[1].values.Status, 'pending');
  });

  it('preserves escaped quotes and embedded line breaks inside quoted CSV cells', () => {
    const parsed = parseCSV('Name,Notes\r\n"Blue ""A"" Team","Line 1\r\nLine 2"\r\n', 10);

    assert.equal(parsed.rows[0].values.Name, 'Blue "A" Team');
    assert.equal(parsed.rows[0].values.Notes, 'Line 1\r\nLine 2');
  });

  it('rejects duplicate column headers after normalization', () => {
    assert.throws(
      () => parseCSV('Team Name,team_name\nBlue Jays,U11\n', 10),
      (error: unknown) => error instanceof ImportParseError && error.message.includes('Duplicate column header'),
    );
  });

  it('enforces data row limits after skipping blank rows', () => {
    assert.throws(
      () => parseCSV('Name\nAlpha\n\nBravo\n', 1),
      (error: unknown) => error instanceof ImportParseError && error.message.includes('limited to 1 data rows'),
    );
  });
});

/**
 * A TITLE ROW ABOVE THE TABLE, AND FOOTNOTES UNDER IT.
 *
 * Real spreadsheets are not bare grids. A coach's own budget opens with the club's name; a bank
 * statement opens with an account line; and since 2026-09-05 our own money reports open with a
 * masthead and close with the footnotes explaining what the figures mean.
 *
 * ⚠⚠ THIS WAS A REAL DEFECT FOR ABOUT AN HOUR (/review, 2026-09-05). The Budget-vs-Actual month
 * export shares its column names with the shape the budget importer reads — so the masthead added
 * that day made a file this product had just produced fail on the way back in, with
 * "Duplicate column header: <the team name>". The reason is worth keeping: a banner is a MERGED
 * cell, and a merged cell reads back with its value mirrored into every column, so the row arrives
 * as the same string N times and trips the duplicate-header check.
 */
describe('a titled spreadsheet still imports', () => {
  it('skips a merged banner and reads the row under it as the header', () => {
    const file = parseCSV(
      'Riverdale Ridge 12U · 2026 Season,Riverdale Ridge 12U · 2026 Season,Riverdale Ridge 12U · 2026 Season\n'
      + 'Category / line,Amount,Notes\n'
      + 'Diamond permits,3200,spring block\n',
      50);
    assert.deepEqual(file.headers, ['Category / line', 'Amount', 'Notes']);
    assert.equal(file.rows.length, 1);
    assert.equal(file.rows[0].values['Category / line'], 'Diamond permits');
  });

  it('skips the footnotes and branding line at the foot', () => {
    const note = 'Cash is money that moved. Revenue is every dollar that arrived.';
    const file = parseCSV(
      `Category / line,Amount\nDiamond permits,3200\n${note},${note}\n`
      + 'Generated by FieldLogicHQ,Generated by FieldLogicHQ\n',
      50);
    assert.equal(file.rows.length, 1, 'a sentence under the table is not a budget line');
    assert.equal(file.rows[0].values['Category / line'], 'Diamond permits');
  });

  it('does NOT eat a single-column file, whose one header is trivially "all the same"', () => {
    const file = parseCSV('Name\nAlpha\nBravo\n', 50);
    assert.deepEqual(file.headers, ['Name']);
    assert.equal(file.rows.length, 2);
  });

  it('does NOT eat a real row that happens to repeat one value across columns', () => {
    /* Two columns holding the same figure is ordinary data. The guard needs EVERY filled cell to be
       identical, so a name in front of two matching numbers is never mistaken for a banner — which
       is exactly the shape of a real budget row that came in bang on plan. */
    const file = parseCSV('Category / line,Budget,Actual\nDiamond permits,3200,3200\n', 50);
    assert.equal(file.rows.length, 1, 'a row whose cells are not ALL identical is data');
    assert.equal(file.rows[0].values['Budget'], '3200');
    assert.deepEqual(file.headers, ['Category / line', 'Budget', 'Actual']);
  });
});
