/**
 * A RECORD THAT BELONGS TO A SEASON IS LOOKED UP BY ITS SEASON — enforced as a shape over
 * `lib/db.ts` rather than remembered route by route.
 *
 * ⚠ WHY THIS EXISTS, PRECISELY. `id + team_id` reads as tight. It is not, for a table keyed by
 * program year: the pair identifies the row across EVERY season the team has ever had, so a write
 * route standing in the live season can reach a finished one by id alone. It bit once for real —
 * a fundraiser in a closed season could be renamed, re-dated and re-opened from an archived Money
 * hub (fixed with migration 237) — and the review that found it noted three siblings written the
 * same way:
 *
 *   · evaluation sessions — the id + team lookup gated the whole run screen, so a closed season's
 *     session could be re-dated, which RE-STAMPS every reading collected in it, or deleted;
 *   · lineup templates — renamable, editable and deletable across seasons;
 *   · the practice recap — its route happened to check the season first, so nothing was reachable,
 *     but the writer itself would take any event id.
 *
 * All three were narrow because no archive door hands out a past id. That is a property of today's
 * NAVIGATION, not of the query — and navigation is exactly what Chunk F changes when a section
 * becomes historical. So the rule is stated here, over the whole data layer: **a scoped write
 * states its own scope.**
 *
 * (Sibling of `coach-season-write-guard.test.ts`, which governs which ROUTES may address a past
 * season. This one governs whether a query can tell the difference at all.)
 */
import assert from 'node:assert/strict';
import { describe, it } from 'node:test';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

const DB = join(process.cwd(), 'lib', 'db.ts');
const COLUMNS = join(process.cwd(), 'docs', 'agents', 'db', 'schema-snapshots', 'schema-dump-columns-dev.json');

/**
 * Tables whose rows belong to ONE season — DERIVED from the committed schema snapshot, never
 * hand-listed.
 *
 * ⚠⚠ IT WAS HAND-LISTED FOR ABOUT AN HOUR, AND THAT WAS ALREADY WRONG. The first draft named
 * eight tables from memory. The live schema has far more carrying `program_year_id`, and one of
 * the omitted ones — `rep_team_game_moments` — held a live instance of the exact defect this file
 * exists to catch. The guard reported "no offenders" over a set that did not include the offender.
 *
 * That is the worse half of the bug it was written to prevent: a guard whose COVERAGE is a
 * hand-kept list decays the same way the convention it replaced did, and reads green while doing
 * it. The snapshot is regenerated by `npm run refresh:snapshots` on every schema change, so
 * deriving from it means a table gains this protection the moment a migration gives it a season —
 * with nobody remembering anything.
 */
function seasonKeyedTables(): string[] {
  const rows = JSON.parse(readFileSync(COLUMNS, 'utf8')) as Array<{ table_name: string; column_name: string }>;
  return [...new Set(
    rows.filter(r => r.column_name === 'program_year_id').map(r => r.table_name),
  )].sort();
}

const SEASON_KEYED_TABLES = seasonKeyedTables();

/**
 * Lookups that are team-scoped ON PURPOSE, each with the reason the season would be wrong there.
 *
 * ⚠ A reason must say why the row is addressed ACROSS seasons deliberately — "it only runs from a
 * live-season route" is not one, because that is the arrangement this guard exists to stop relying
 * on.
 */
const CROSS_SEASON_BY_DESIGN: Array<{ fn: string; reason: string }> = [];

/**
 * Every `supabaseAdmin.from('<table>')…;` chain in the data layer, with the enclosing function's
 * name for the failure message.
 *
 * Chains terminate at the first `;` — every query in this file is written as one statement, and
 * the assertion at the bottom fails if that ever stops being true for enough of them to matter.
 */
function queryChains(source: string): { table: string; fn: string; chain: string; line: number }[] {
  const out: { table: string; fn: string; chain: string; line: number }[] = [];
  const fromRe = /\.from\(\s*['"]([a-z_]+)['"]\s*\)/g;
  let match: RegExpExecArray | null;
  while ((match = fromRe.exec(source)) !== null) {
    const table = match[1];
    if (!SEASON_KEYED_TABLES.includes(table)) continue;
    const end = source.indexOf(';', match.index);
    const chain = source.slice(match.index, end < 0 ? source.length : end);
    const before = source.slice(0, match.index);
    // The nearest `export async function name(` above this chain.
    const fnMatches = [...before.matchAll(/export (?:async )?function (\w+)/g)];
    out.push({
      table,
      fn: fnMatches.length ? fnMatches[fnMatches.length - 1][1] : '(top level)',
      chain,
      line: before.split('\n').length,
    });
  }
  return out;
}

/** Does this chain address ONE row by id, alongside a team, without saying which season? */
function isUnscopedByIdAndTeam(chain: string): boolean {
  const byId = /\.eq\(\s*['"](id|event_id)['"]/.test(chain);
  const byTeam = /\.eq\(\s*['"]team_id['"]/.test(chain);
  const byYear = /\.eq\(\s*['"]program_year_id['"]/.test(chain);
  return byId && byTeam && !byYear;
}

describe('a season-keyed record is never addressed by id + team alone', () => {
  const source = readFileSync(DB, 'utf8');
  const chains = queryChains(source);

  it('derives its table set from the live schema, and that set is not tiny', () => {
    assert.ok(
      SEASON_KEYED_TABLES.length >= 25,
      `expected the season-keyed tables from the snapshot, found ${SEASON_KEYED_TABLES.length}. `
      + 'If the snapshot moved or changed shape this guard is scanning almost nothing and passing.',
    );
    // The four families the fix of 2026-08-15 covered must all be in the derived set — if the
    // derivation silently stopped finding them, the guard would go quiet on its own subject.
    for (const t of ['rep_team_events', 'rep_team_evaluation_sessions', 'rep_team_lineup_templates', 'rep_team_game_moments']) {
      assert.ok(SEASON_KEYED_TABLES.includes(t), `${t} is season-keyed but the derivation missed it`);
    }
  });

  it('finds the season-keyed queries at all (guards against a vacuous pass)', () => {
    assert.ok(
      chains.length > 20,
      `expected the data layer's season-keyed queries, found ${chains.length}. If the query style `
      + 'changed, fix the extractor — a guard that finds nothing passes every time.',
    );
  });

  it('has no id + team lookup that cannot tell one season from another', () => {
    const exempt = new Set(CROSS_SEASON_BY_DESIGN.map(e => e.fn));
    const offenders = chains
      .filter(c => !exempt.has(c.fn) && isUnscopedByIdAndTeam(c.chain))
      .map(c => `lib/db.ts:${c.line}  ${c.fn}()  →  ${c.table} by id + team_id, no program_year_id`);

    assert.deepEqual(
      offenders,
      [],
      'These queries address a season-keyed row by id and team only. That pair identifies the row '
      + 'in EVERY season the team has had, so a live-season route can reach a finished season by id '
      + '— which is how an archived fundraiser became editable (fixed, migration 237). Add '
      + '.eq(\'program_year_id\', …) and take the season as a parameter, or add the function to '
      + 'CROSS_SEASON_BY_DESIGN with the reason it must span seasons:\n  '
      + offenders.join('\n  '),
    );
  });

  it('lists a reason for every deliberate cross-season lookup', () => {
    for (const entry of CROSS_SEASON_BY_DESIGN) {
      assert.ok(
        entry.reason.trim().length > 30,
        `${entry.fn} is exempt without a real reason — say why it must span seasons.`,
      );
    }
  });

  it('proves it can still see the offence (the guard is not looking at nothing)', () => {
    assert.ok(
      isUnscopedByIdAndTeam(`.from('rep_team_lineup_templates').delete().eq('id', id).eq('team_id', teamId)`),
      'the guard no longer recognises the exact shape it was written for',
    );
    assert.ok(
      !isUnscopedByIdAndTeam(`.from('rep_team_lineup_templates').delete().eq('id', id).eq('team_id', teamId).eq('program_year_id', pyId)`),
      'the guard flags a correctly-scoped query, which will teach the next reader to work around it',
    );
  });
});
